name: Coverage

on: ["push"]

jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Vality-ESLint
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: ./.github/actions/setup
      - name: Run Jest
        run: pnpm test
      - name: Upload to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
